services:
  db:
    image: postgres:16
    container_name: inventory_postgres
    restart: always
    environment:
      POSTGRES_DB: PruebaTecnica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d PruebaTecnica"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de Backup Automatizado
  db-backup:
    image: prodrigestivill/postgres-backup-local:16
    container_name: inventory_db_backup
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: PruebaTecnica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      SCHEDULE: "*/15 * * * *"  # Realiza el respaldo al inicio de cada hora 
      BACKUP_KEEP_DAYS: 7
      BACKUP_SUFFIX: .sql
    volumes:
      - ./backups:/backups # Carpeta local donde se guardarán los dumps
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./Inventory-System
      dockerfile: Dockerfile
    container_name: inventory_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/PruebaTecnica
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Inventory-System-Frontend
      dockerfile: Dockerfile
    container_name: inventory_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data: