-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.audit_log
(
    fecha timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descripcion character varying(2000) COLLATE pg_catalog."default",
    error_mensaje character varying(2000) COLLATE pg_catalog."default",
    accion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    resultado character varying(255) COLLATE pg_catalog."default" NOT NULL,
    usuario character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.branch
(
    latitude double precision,
    longitude double precision,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    id uuid NOT NULL,
    address character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT branch_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    average_cost numeric(12, 2) DEFAULT 0,
    min_stock numeric(12, 2),
    quantity numeric(12, 2) NOT NULL DEFAULT 0,
    sale_price numeric(12, 2) DEFAULT 0,
    updated_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    branch_id uuid NOT NULL,
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory_transaction
(
    quantity numeric(12, 2) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    branch_id uuid NOT NULL,
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    reference_id uuid,
    user_id uuid,
    reference_type character varying(50) COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    reason character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT inventory_transaction_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    id uuid NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default",
    sku character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_price
(
    price numeric(12, 2) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    effective_from timestamp(6) with time zone,
    effective_to timestamp(6) with time zone,
    currency character varying(10) COLLATE pg_catalog."default",
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    label character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT product_price_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_provider
(
    product_id uuid NOT NULL,
    provider_id uuid NOT NULL,
    CONSTRAINT product_provider_pkey PRIMARY KEY (product_id, provider_id)
);

CREATE TABLE IF NOT EXISTS public.provider
(
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    id uuid NOT NULL,
    contact_info character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT provider_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.purchase
(
    discount_total numeric(12, 2),
    subtotal numeric(12, 2),
    tax numeric(12, 2),
    total numeric(12, 2),
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    expected_delivery_date timestamp(6) with time zone,
    branch_id uuid NOT NULL,
    id uuid NOT NULL,
    provider_id uuid,
    user_id uuid,
    supplier_notes character varying(1000) COLLATE pg_catalog."default",
    payment_terms character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT purchase_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.purchase_detail
(
    discount numeric(12, 2),
    price numeric(12, 2) NOT NULL,
    quantity numeric(12, 2) NOT NULL,
    received_quantity numeric(12, 2),
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    purchase_id uuid NOT NULL,
    CONSTRAINT purchase_detail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sale
(
    total numeric(12, 2),
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    branch_id uuid NOT NULL,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT sale_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sale_detail
(
    price numeric(12, 2) NOT NULL,
    quantity numeric(12, 2) NOT NULL,
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    sale_id uuid NOT NULL,
    CONSTRAINT sale_detail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stock_alert
(
    id uuid NOT NULL,
    branch_id uuid NOT NULL,
    created_by uuid,
    notified_at timestamp(6) with time zone,
    product_id uuid NOT NULL,
    urgency character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT stock_alert_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transfer
(
    actual_transit_minutes integer,
    route_cost numeric(18, 2),
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    dispatched_at timestamp(6) with time zone,
    estimated_arrival timestamp(6) with time zone,
    received_at timestamp(6) with time zone,
    shipped_at timestamp(6) with time zone,
    approved_by uuid,
    created_by uuid,
    destination_branch_id uuid NOT NULL,
    id uuid NOT NULL,
    origin_branch_id uuid NOT NULL,
    route_priority character varying(20) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    carrier character varying(200) COLLATE pg_catalog."default",
    route_id character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT transfer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transfer_alert
(
    id uuid NOT NULL,
    created_at timestamp(6) with time zone,
    missing_quantity numeric(12, 2),
    product_id uuid,
    status character varying(50) COLLATE pg_catalog."default",
    transfer_id uuid,
    CONSTRAINT transfer_alert_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transfer_detail
(
    quantity numeric(12, 2) NOT NULL,
    quantity_confirmed numeric(12, 2),
    received_quantity numeric(12, 2),
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    transfer_id uuid NOT NULL,
    CONSTRAINT transfer_detail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP,
    branch_id uuid,
    id uuid NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fkk2cskrccyjpsc9m1dhtsg20om FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fkp7gj4l80fx8v0uap3b2crjwp5 FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inventory_transaction
    ADD CONSTRAINT fkadysxy0xx1oug9ljtg47bkcny FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventory_transaction
    ADD CONSTRAINT fkl412lwgippk0pio40g7bg73l6 FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventory_transaction
    ADD CONSTRAINT fknh219tif98580jbsud121mpt1 FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.product_price
    ADD CONSTRAINT fkeupemu63ifqfc4txkskyy1hyi FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_provider
    ADD CONSTRAINT fk8k2abv638cudmuv7ak293ymk5 FOREIGN KEY (provider_id)
    REFERENCES public.provider (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_provider
    ADD CONSTRAINT fkaopwfa83ihjrlbcbgjqxqvhc7 FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fk38uls8a8efvkiwfnf2jodg8g5 FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fkdy7v556ts4pyi0qhrak3oglre FOREIGN KEY (provider_id)
    REFERENCES public.provider (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fkru2t2vbe7fdniy7m2r5cevg5c FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase_detail
    ADD CONSTRAINT fk65hoe4yy1817l2vm74msb8eq5 FOREIGN KEY (purchase_id)
    REFERENCES public.purchase (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchase_detail
    ADD CONSTRAINT fk79a6tsn4e9qfillme2u9kr3i2 FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sale
    ADD CONSTRAINT fkdqg684jc1qmwmwvems0exvhnj FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.sale
    ADD CONSTRAINT fkh2cd9nx03d965i90vdfojqvi5 FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sale_detail
    ADD CONSTRAINT fk2k26c5k0qkdm1srkiwn7q5009 FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sale_detail
    ADD CONSTRAINT fkgnpg9v1mvi1nyhc18vdcyuh98 FOREIGN KEY (sale_id)
    REFERENCES public.sale (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.transfer
    ADD CONSTRAINT fk4yy158gpul9fiqi846y6rj7wu FOREIGN KEY (created_by)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.transfer
    ADD CONSTRAINT fkk0yoclsg1v2sj1e9skod99c1a FOREIGN KEY (destination_branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transfer
    ADD CONSTRAINT fkkv07w027u61ho8rp7awqafnhy FOREIGN KEY (approved_by)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.transfer
    ADD CONSTRAINT fkl80mko7q94jooc1arasq6kfge FOREIGN KEY (origin_branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transfer_alert
    ADD CONSTRAINT fkthbt7cc4ixukh1m38p6q9rggm FOREIGN KEY (transfer_id)
    REFERENCES public.transfer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transfer_detail
    ADD CONSTRAINT fk645iajto80nxdyb7o11vu6agr FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transfer_detail
    ADD CONSTRAINT fk9oeu1clo1tyxonahctnvay6us FOREIGN KEY (transfer_id)
    REFERENCES public.transfer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT fkr1hrpktd3wu9a4qaopdrkh44g FOREIGN KEY (branch_id)
    REFERENCES public.branch (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;