spring.application.name=inventory-system
server.port=8080

# ===============================
# DATABASE (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/PruebaTecnica
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
app.migrate-plaintext-passwords=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# EMAIL (SMTP)
# ===============================
app.mail.username=juansepulveda8010@gmail.com
app.mail.password=ukwv yeqq gphc jzkk
app.mail.host=smtp.gmail.com
app.mail.port=587
app.mail.transport-strategy=SMTP_TLS
